server_connect_timeout: 5000
listeners:
- query_port: 25577
  motd: '&9 spoopy server'
  tab_list: GLOBAL_PING
  query_enabled: true
  proxy_protocol: false
  forced_hosts:
    example.com: pvp
  ping_passthrough: false
  priorities:
  - main
  bind_local_address: true
  host: 0.0.0.0:25623
  max_players: 9999
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.list
  - bungeecord.command.server
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 100000
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: fd7147ea-d904-494b-85d8-c74b3c8ea79d
online_mode: true
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  main:
    motd: Main Server... how can you see this?
    address: 51.222.208.92:25568
    restricted: true
  queue:
    motd: '&1heh, queue'
    address: 51.222.121.148:25624
    restricted: true
